### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by ghost** [mgjeong/device-opcua-java#7]
Environment: Virtual Machine with Ubuntu:
`Linux ubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`

**Steps:**
- Cloned this repository
- Executed the file Dockerize.sh
- Added device-opcua-java into a docker-compose.yml file including also other EdgeX services
- Executed: docker-compose start

**Result:**
device-opcua-java service immeditaly exit with following error:

```
ubuntu@ubuntu:~$ sudo docker-compose logs -f device-opcua-java
Attaching to device-opcua-java
device-opcua-java    | standard_init_linux.go:190: exec user process caused "exec format error"
device-opcua-java    | standard_init_linux.go:190: exec user process caused "exec format error"
device-opcua-java    | standard_init_linux.go:190: exec user process caused "exec format error"
device-opcua-java    | standard_init_linux.go:190: exec user process caused "exec format error"
device-opcua-java exited with code 1
```

**Comment by jeremylin06** [comment]
The problem is with the Dockerfile. I changed the line:
CMD ["./run.sh"]
 to
 CMD ["sh", "-c", "./run.sh"]
and build again, and got it to start successfully.
